# Question 7

## Two versions of a website are tested. Out of 500 users for Version A, 320 users click the signup button. Out of 480 users for Version B, 290 users click the signup button. At the 5% level of significance, test whether the conversion rates differ.

## Test : Two-sample proportion test(two tailed)
## H0(Null Hypothesis): p1 = p2 : The conversion rate of version A and version B for the website is equal.
## H1(Alternate Hypothesis: p1 != p2 : The conversion rate of version A and version B for the website differs.

In [1]:
# Version A
n1 = 500          # Total number of users who tested Version A
success1 = 320    # Number of users who clicked the signup button in Version A

# Version B
n2 = 480          # Total number of users who tested Version B
success2 = 290    # Number of users who clicked the signup button in Version B

alpha = 0.05      # Significance level = 5%

In [2]:
conversion_rate1 = success1 / n1  # Conversion rate = users who clicked / total users for Version A
conversion_rate2 = success2 / n2  # Conversion rate = users who clicked / total users for Version B

print("Version A conversion rate:", conversion_rate1)  # Shows the conversion rate for Version A
print("Version B conversion rate:", conversion_rate2)  # Shows the conversion rate for Version B

Version A conversion rate: 0.64
Version B conversion rate: 0.6041666666666666


In [3]:
# For a two-sample proportion test, we use a pooled proportion under H₀
pooled_proportion = (success1 + success2) / (n1 + n2)  # Combined conversion rate assuming H0: p1 = p2

print("Pooled proportion:", pooled_proportion)  # Shows the combined conversion rate

Pooled proportion: 0.6224489795918368


In [5]:
# calculate the standard Error:
import math
standard_error = math.sqrt(pooled_proportion * (1 - pooled_proportion) * (1/n1 + 1/n2))  # SE of the difference between the two conversion rates

print("Standard Error:", standard_error)  # Shows the expected variation in the difference between sample conversion rates

Standard Error: 0.030977553866266053


In [6]:
# calculate the z-statistic:
z_statistic = (conversion_rate1 - conversion_rate2) / standard_error  # Difference between the two sample conversion rates divided by SE

print("z-statistic:", z_statistic)  # Shows how many standard errors the observed difference is from 0

z-statistic: 1.1567515462334546


In [7]:
# calculate the p_value
from scipy import stats

p_value = 2 * stats.norm.sf(abs(z_statistic))  # Two-tailed p-value: considers both directions of difference

print("p-value:", p_value)  # Probability of observing this difference if H0 is true

p-value: 0.24737388327470267


In [8]:
if p_value < alpha:  # If p-value is less than the 5% significance level
    print("Reject H0")
else:
    print("Fail to reject H0")

Fail to reject H0


## At the 5% level of significance, we fail to reject H₀. There is insufficient statistical evidence to conclude that the conversion rates of Version A and Version B are different.

# Question 8

## A vaccine is tested in two regions. In Region A, 180 out of 300 people recover. In Region B, 165 out of 310 people recover. At the 5% level of significance, test whether the recovery rates are significantly different.

## Test: Two-sample proportion test, two-tailed
## H₀(Null Hypothesis): p₁ = p₂ — The recovery rates in Region A and Region B are equal.
## H1(Alternate Hypothesis): p₁ ≠ p₂ — The recovery rates in Region A and Region B are different.

In [9]:
# Region A
n1 = 300          # Total number of people tested in Region A
success1 = 180    # Number of people who recovered in Region A

# Region B
n2 = 310          # Total number of people tested in Region B
success2 = 165    # Number of people who recovered in Region B

alpha = 0.05      # Significance level = 5%

In [10]:
# calculate the recovery rates
recovery_rate1 = success1 / n1  # Recovery rate = recovered people / total people in Region A
recovery_rate2 = success2 / n2  # Recovery rate = recovered people / total people in Region B

print("Region A recovery rate:", recovery_rate1)  # Shows the recovery rate for Region A
print("Region B recovery rate:", recovery_rate2)  # Shows the recovery rate for Region B

Region A recovery rate: 0.6
Region B recovery rate: 0.532258064516129


In [ ]:
# Region A = 60% , Region B ≈ 53.23%

In [11]:
#Calculate the pooled proportion
pooled_proportion = (success1 + success2) / (n1 + n2)  # Combined recovery rate assuming H0: p1 = p2

print("Pooled proportion:", pooled_proportion)  # Shows the combined recovery rate

Pooled proportion: 0.5655737704918032


In [12]:
# Calculate the Standard Error
import math

standard_error = math.sqrt(pooled_proportion * (1 - pooled_proportion) * (1/n1 + 1/n2))  # SE of the difference between the two recovery rates

print("Standard Error:", standard_error)  # Shows the expected variation in the difference between the sample recovery rates

Standard Error: 0.04014450365843399


In [13]:
# Calculate the z-statistic
z_statistic = (recovery_rate1 - recovery_rate2) / standard_error  # Difference between the two recovery rates divided by SE

print("z-statistic:", z_statistic)  # Shows how many standard errors the observed difference is from 0

z-statistic: 1.6874523112864297


In [14]:
#Calculate the p-value
from scipy import stats

p_value = 2 * stats.norm.sf(abs(z_statistic))  # Two-tailed p-value: considers both directions of difference

print("p-value:", p_value)  # Probability of observing this difference if H0 is true

p-value: 0.09151641239095082


In [15]:
if p_value < alpha:  # If p-value is less than the 5% significance level
    print("Reject H0")
else:
    print("Fail to reject H0")

Fail to reject H0


In [ ]:
# The observed recovery rates are 60% in Region A and 53.23% in Region B, but the difference is not statistically significant at the 5% level.

## At the 5% level of significance, we fail to reject H₀. There is insufficient statistical evidence to conclude that the recovery rates between Region A and Region B are significantly different.

# Question 9

## A company wants to compare the average productivity of employees trained using three different training programs. Program A has 25 employees with a mean productivity score of 80 and a standard deviation of 8. Program B has 30 employees with a mean of 75 and a standard deviation of 7. Program C has 28 employees with a mean of 82 and a standard deviation of 6. At the 5% level of significance, test whether there is a difference in mean productivity across the programs.

## Test :  ANOVA - One-way
## H0(Null Hypothesis) : μ1 = μ2 = μ3 : The mean productivity scores are equal across all three programs
## H1(Alternate Hypothesis) : μ1 != μ2 != μ3 : Not all three mean of productivity scores are equal.

In [17]:
# Program A
n1 = 25          # Number of employees in Program A
mean1 = 80       # Mean productivity score for Program A
std1 = 8         # Standard deviation of productivity scores in Program A

# Program B
n2 = 30          # Number of employees in Program B
mean2 = 75       # Mean productivity score for Program B
std2 = 7         # Standard deviation of productivity scores in Program B

# Program C
n3 = 28          # Number of employees in Program C
mean3 = 82       # Mean productivity score for Program C
std3 = 6         # Standard deviation of productivity scores in Program C

alpha = 0.05     # Significance level = 5%

In [18]:
# Calculate the overall (grand) mean
grand_mean = ((n1 * mean1) + (n2 * mean2) + (n3 * mean3)) / (n1 + n2 + n3)  # Overall mean productivity, weighted by number of employees

print("Grand mean:", grand_mean)  # Shows the overall mean across all three programs

Grand mean: 78.86746987951807


In [19]:
# Calculate the Between-Group Sum of Squares (SSB)
# This measures how much the three program means differ from the overall mean.
ssb = (n1 * (mean1 - grand_mean)**2) + (n2 * (mean2 - grand_mean)**2) + (n3 * (mean3 - grand_mean)**2)  # Variation between the three program means

print("Between-group Sum of Squares (SSB):", ssb)  # Shows the variation caused by differences between program means

Between-group Sum of Squares (SSB): 755.5421686746988


In [20]:
# Calculate the Within-Group Sum of Squares (SSW).This measures the variation among individual employees within each training program.
ssw = ((n1 - 1) * std1**2) + ((n2 - 1) * std2**2) + ((n3 - 1) * std3**2)  # Variation within each training program

print("Within-group Sum of Squares (SSW):", ssw)  # Shows the variation among employees within the programs

Within-group Sum of Squares (SSW): 3929


In [21]:
# Calculate Degrees of Freedom.For one-way ANOVA, two degrees of freedom required
k = 3                                  # Number of training programs
N = n1 + n2 + n3                      # Total number of employees

df_between = k - 1                    # Degrees of freedom between the programs
df_within = N - k                     # Degrees of freedom within the programs

print("df between:", df_between)      # Used for the between-group variation
print("df within:", df_within)        # Used for the within-group variation

df between: 2
df within: 80


In [22]:
# Calculate Mean Squares.divide each Sum of Squares by its corresponding degrees of freedom:
ms_between = ssb / df_between  # Mean Square Between = variation between program means / df between

ms_within = ssw / df_within    # Mean Square Within = variation within programs / df within

print("Mean Square Between:", ms_between)  # Average variation between the three program means
print("Mean Square Within:", ms_within)    # Average variation among employees within the programs

Mean Square Between: 377.7710843373494
Mean Square Within: 49.1125


In [23]:
# Calculate the F-statistic.The ANOVA F-statistic compares between-group variation with within-group variation
f_statistic = ms_between / ms_within  # F-statistic = between-group variation / within-group variation

print("F-statistic:", f_statistic)  # Shows how large the between-program variation is compared with within-program variation

F-statistic: 7.691953867902254


In [24]:
# Calculate the p-value.For ANOVA, we use the F-distribution with: Numerator df = 2; Denominator df = 80
from scipy import stats

p_value = stats.f.sf(f_statistic, df_between, df_within)  # Right-tail probability from the F-distribution

print("p-value:", p_value)  # Probability of observing an F-statistic this large if H0 is true

p-value: 0.0008802277285803062


In [25]:
if p_value < alpha:  # If p-value is less than the 5% significance level
    print("Reject H0")
else:
    print("Fail to reject H0")

Reject H0


## At the 5% level of significance, we reject H₀. There is sufficient statistical evidence to conclude that mean productivity is not the same across all three training programs.

# Question 10

## A company wants to test whether gender and product preference are independent. The survey results are as follows:
## ●	Male: 60 prefer Product A, 40 prefer Product B
## ●	Female: 50 prefer Product A, 50 prefer Product B
## At the 5% level of significance, test for independence.


### Test: Chi-square test of independence

### Hypotheses

### H₀: Gender and product preference are independent.Gender does not have a significant association with product preference.

### H₁: Gender and product preference are not independent.There is a significant association between gender and product preference.

In [26]:
# Step 1 — Create the observed frequency table
import numpy as np

observed = np.array([
    [60, 40],  # Male: 60 prefer Product A, 40 prefer Product B
    [50, 50]   # Female: 50 prefer Product A, 50 prefer Product B
])

print(observed)  # Displays the observed frequencies

[[60 40]
 [50 50]]


In [27]:
# Step 2 — Calculate the expected frequencies.For a Chi-square test of independence, the expected frequency is:
# Expected = (Row total × Column total) / Grand total

row_totals = observed.sum(axis=1)  # Total responses for each gender
column_totals = observed.sum(axis=0)  # Total responses for each product
grand_total = observed.sum()  # Total number of survey responses

expected = np.outer(row_totals, column_totals) / grand_total  # Calculate expected frequencies assuming H0 is true

print("Expected frequencies:")
print(expected)  # Shows the frequencies we would expect if gender and product preference were independent

Expected frequencies:
[[55. 45.]
 [55. 45.]]


In [28]:
# Step3— Calculate the Chi-square statistic.The Chi-square statistic measures how much the observed frequencies differ from the expected frequencies.

chi_square = np.sum((observed - expected)**2 / expected)  # Sum of the differences between observed and expected frequencies

print("Chi-square statistic:", chi_square)  # Shows the overall difference between observed and expected frequencies

Chi-square statistic: 2.0202020202020203


In [29]:
# Step 4 — Calculate the degrees of freedom.For a Chi-square test of independence:
# df = (number of rows - 1) × (number of columns - 1)
rows, columns = observed.shape  # Get the number of rows and columns in the observed table

df = (rows - 1) * (columns - 1)  # Degrees of freedom for a Chi-square test of independence

print("Degrees of freedom:", df)  # Shows the degrees of freedom

Degrees of freedom: 1


In [30]:
# Step 5 — Calculate the p-value
#For the Chi-square test, we use the right tail of the Chi-square distribution:
from scipy import stats

p_value = stats.chi2.sf(chi_square, df)  # Right-tail probability for the Chi-square statistic

print("p-value:", p_value)  # Probability of observing this Chi-square value if H0 is true

p-value: 0.15521848968468005


In [31]:
if p_value < alpha:  # If p-value is less than the 5% significance level
    print("Reject H0")
else:
    print("Fail to reject H0")

Fail to reject H0


## At the 5% level of significance, we fail to reject H₀. There is insufficient statistical evidence to conclude that gender and product preference are associated.

# Question 11

## 11.	A  hospital studies whether smoking status is related to disease occurrence. The data collected is as follows:
## ●	Smokers: 70 have the disease, 30 do not
## ●	Non-smokers: 40 have the disease, 60 do not
## At the 5% level of significance, test whether smoking status and disease occurrence are independent. 


### Test: Chi-square test of independence

### H₀: Smoking status and disease occurrence are independent. There is no significant association between smoking status and disease occurrence.

### H₁: Smoking status and disease occurrence are not independent. There is a significant association between smoking status and disease occurrence.

In [32]:
# Step 1 — Create the observed frequency table
import numpy as np

observed = np.array([
    [70, 30],  # Smokers: 70 have the disease, 30 do not
    [40, 60]   # Non-smokers: 40 have the disease, 60 do not
])

print(observed)  # Displays the observed frequencies

[[70 30]
 [40 60]]


In [33]:
# Step 2 — Calculate the expected frequencies
row_totals = observed.sum(axis=1)  # Total people in each smoking-status group
column_totals = observed.sum(axis=0)  # Total people with and without the disease
grand_total = observed.sum()  # Total number of people in the study

expected = np.outer(row_totals, column_totals) / grand_total  # Expected frequencies assuming H0 is true

print("Expected frequencies:")
print(expected)  # Shows the frequencies expected if smoking status and disease occurrence are independent

Expected frequencies:
[[55. 45.]
 [55. 45.]]


In [34]:
# Step 3 — Calculate the Chi-square statistic
chi_square = np.sum((observed - expected)**2 / expected)  # Measures how much the observed frequencies differ from the expected frequencies

print("Chi-square statistic:", chi_square)  # Shows the overall difference between observed and expected frequencies

Chi-square statistic: 18.18181818181818


In [35]:
# Step 4: Calculate degrees of freedom For a chi-square test of independence:df=(rows−1)(columns−1)
df = (observed.shape[0] - 1) * (observed.shape[1] - 1)  # Calculate degrees of freedom

print("Degrees of freedom:", df)  # Display the degrees of freedom

Degrees of freedom: 1


In [36]:
# Step 5: Calculate the p-value We already have:
#Chi-square statistic = 18.1818
#Degrees of freedom = 1
#Now use the chi-square distribution to calculate the right-tail p-value:
from scipy.stats import chi2

p_value = chi2.sf(chi_square, df)  # Calculate the right-tail p-value

print("p-value:", p_value)  # Display the p-value

p-value: 2.0078656124264854e-05


In [37]:
if p_value < alpha:  # Compare the p-value with the significance level
    print("Reject H0")  # There is sufficient evidence against the null hypothesis
else:
    print("Fail to reject H0")  # There is not enough evidence against the null hypothesis

Reject H0


## At the 5% significance level, there is sufficient statistical evidence to conclude that smoking status and disease occurrence are associated. Therefore, they are not independent.

# Question 12
## A dice manufacturer claims that a die is fair. The die is rolled 120 times, and the observed frequencies are:
#### ●	Face 1: 18
#### ●	Face 2: 22
#### ●	Face 3: 20
#### ●	Face 4: 25
#### ●	Face 5: 17
#### ●	Face 6: 18
#### At the 5% level of significance, test whether the die is fair.


## Test: Chi-square goodness-of-fit test
## H₀: The die is fair; each face has probability (1/6).
## H1: The die is not fair; at least one face has a probability different from (1/6).

In [38]:
import numpy as np

observed = np.array([18, 22, 20, 25, 17, 18])  # Observed number of rolls for faces 1 to 6

print(observed)  # Display the observed frequencies

[18 22 20 25 17 18]


In [39]:
total_rolls = observed.sum()  # Total number of die rolls

expected = np.full(6, total_rolls / 6)  # Expected frequency for each face if the die is fair

print("Expected frequencies:", expected)  # Display the expected frequencies

Expected frequencies: [20. 20. 20. 20. 20. 20.]


In [40]:
chi_square = np.sum((observed - expected)**2 / expected)  # Calculate the chi-square statistic

print("Chi-square statistic:", chi_square)  # Display the chi-square value

Chi-square statistic: 2.3000000000000003


In [41]:
df = len(observed) - 1  # Number of categories minus 1

print("Degrees of freedom:", df)  # Display the degrees of freedom

Degrees of freedom: 5


In [42]:
from scipy.stats import chi2

p_value = chi2.sf(chi_square, df)  # Calculate the right-tail p-value

print("p-value:", p_value)  # Display the p-value

p-value: 0.8062668698851285


In [43]:
alpha = 0.05  # Significance level = 5%

if p_value < alpha:  # Compare the p-value with the significance level
    print("Reject H0")  # There is sufficient evidence that the die is not fair
else:
    print("Fail to reject H0")  # There is not enough evidence to conclude that the die is not fair

Fail to reject H0


## At the 5% significance level, there is insufficient statistical evidence to conclude that the die is unfair. The observed frequencies are consistent with the expected frequencies of a fair die.